// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kufyvfjylvzdvawknhvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Znl2Zmp5bHZ6ZHZhd2tuaHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNjk5NDUsImV4cCI6MjA3MTY0NTk0NX0.gNt3_DFjfcA6dH8vg88ap2Mijx-B0kY2Li7hKin0piM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});